namespace Marty.Net.Contracts.Exceptions;

using System;

/// <summary>
///     An exception when an event is detected in a stream that was not generated by Marty.Net
/// </summary>
public class UnknownEventAppeared : Exception
{
    internal UnknownEventAppeared(string streamId, string eventId)
        : base($"Event with id {eventId} found in {streamId} not generated by Marty.Net")
    {
        EventId = eventId;
        StreamId = streamId;
    }

    /// <summary>
    ///     The name of the stream
    /// </summary>
    public string EventId { get; }

    /// <summary>
    ///     The name of the stream
    /// </summary>
    public string StreamId { get; }
}
